tasks:
  - init: pip install -e packages/hagrid
    command: hagrid quickstart
ports:
  - name: Jupyter
    port: 8888
    onOpen: open-browser
    visibility: public
  - name: Nodes
    port: 9081-9083
    onOpen: open-browser
    visibility: public
