---
- name: Delete build directory
  shell: "rm -rf {{ build_dir }}"
  become: yes
  when: vagrant is not defined and install == "true"

- name: Copy code checkout to build
  ansible.builtin.copy:
    src: "{{ syft_dir }}/"
    dest: "{{ build_dir }}"
    force: yes
    remote_src: yes
    owner: "{{ om_user }}"
    group: "{{ om_user }}"
  become_user: "{{ om_user }}"
  ignore_errors: yes
  when: vagrant is not defined and install == "true"

- name: Install HAGrid
  shell: "runuser -l {{ om_user }} -c 'pip install -e {{ build_dir }}/packages/hagrid'"
  become: yes
  when: vagrant is not defined and install == "true"

- name: Install HAGrid
  shell: "runuser -l {{ om_user }} -c 'pip install -e {{ syft_dir }}/packages/hagrid'"
  become: yes
  when: vagrant is defined and install == "true"
